new TypeIt("#type-effect", { 
    lifeLike: false, 
    speed: 0 
})
    .type("F")
    .pause(494)
    .type("r")
    .pause(91)
    .type("o")
    .pause(127)
    .type("n")
    .pause(222)
    .type("t")
    .pause(1076)
    .type("e")
    .pause(85)
    .type("n")
    .pause(65)
    .type("d")
    .pause(133)
    .type(" ")
    .pause(639)
    .type("D")
    .pause(210)
    .type("e")
    .pause(237)
    .type("v")
    .pause(190)
    .type("e")
    .pause(194)
    .type("l")
    .pause(166)
    .type("o")
    .pause(130)
    .type("p")
    .pause(152)
    .type("e")
    .pause(96)
    .type("r")
    .pause(71)
    .type(" ")
    .pause(525)
    .delete(1)
    .pause(162)
    .type("!")
    .pause(488)
    .delete(1)
    .go();